### ISSUE TITLE
Where's `getprop`?

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-tools#102]
```sh
dpkg -S getprop
```
stdout:
```
termux-tools: /data/data/com.termux/files/usr/bin/getprop
```

Why can't I find that wrapper script in this repo?

**Comment by twaik** [comment]
Because it is generated in `Makefile.in` using `wrapper-rule` function.

**Comment by Rudxain** [comment]
> Because it is generated in `Makefile.am` using `wrapper-rule` function.

Thanks for the info! And I'm sorry, I should've cloned and `grep`ed the repo (I opened the root `Makefile`, but didn't notice the one in `scripts/`)
