### ISSUE TITLE
pkg install upgrade is unnable to find a mirror working or all mirrors are down 

### ISSUE THREAD

**Issue by Nacport** [termux/termux-tools#104]
$ pkg install upgrade
Checking availability of current mirror: /data/data/com.termux/files/usr/bin/pkg: line 43: 15064 Aborted                 curl --connect-timeout 5 --user-agent 'Termux-PKG/1.0 mirror-checker' --head --fail --location "${current_mirror%/}/dists/stable/Release" > /dev/null 2>&1
bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: /data/data/com.termux/files/usr/bin/pkg: line 78: 15066 Aborted                 curl --connect-timeout 5 --user-agent 'Termux-PKG/1.0 mirror-checker' --head --fail --location "${mirrors[$w]%/}/dists/stable/Release" > /dev/null 2>&1
bad
[*] https://grimler.se/termux-packages-24: /data/data/com.termux/files/usr/bin/pkg: line 78: 15071 Aborted                 curl --connect-timeout 5 --user-agent 'Termux-PKG/1.0 mirror-checker' --head --fail --location "${mirrors[$w]%/}/dists/stable/Release" > /dev/null 2>&1
bad
[*] https://main.termux-mirror.ml/: /data/data/com.termux/files/usr/bin/pkg: line 78: 15074 Aborted                 curl --connect-timeout 5 --user-agent 'Termux-PKG/1.0 mirror-checker' --head --fail --location "${mirrors[$w]%/}/dists/stable/Release" > /dev/null 2>&1
bad
[*] https://termux.mentality.rip/termux-packages-24: /data/data/com.termux/files/usr/bin/pkg: line 78: 15077 Aborted                 curl --connect-timeout 5 --user-agent 'Termux-PKG/1.0 mirror-checker' --head --fail --location "${mirrors[$w]%/}/dists/stable/Release" > /dev/null 2>&1
bad
Using fallback mirror: https://termux.org/packages
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package upgrade

(it's incapable of connect with the pages. it runs out of time every single attempt (I'm new on termux but it worked the last time I used it. Maybe I'm to inexperienced to know what's happening))

**Comment by agnostic-apollo** [comment]
Reinstall app from fdroid or github.

https://github.com/termux/termux-app#Installation
