### ISSUE TITLE
New mirror in Ashburn, VA, United States

### ISSUE THREAD

**Issue by FranGamer1892** [termux/termux-tools#108]
Hello, I've set up the following mirror for termux-main, termux-x11 and termux-root. I am not sure if I have to make the pull request. If so, please tell me and I will do it ASAP. Thanks!
- **Hostname:** [gnlug.org/pub/termux](https://gnlug.org/pub/termux/)
- **Location:** Ashburn, VA, United States
- **Bandwidth:** 1 Gbps
- **Supported protocols:** HTTP, HTTPS, rsync
- **Update frequency:** Syncs every 6 hours
- **IP version:** IPv4/IPv6

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-gnlug) .
