### ISSUE TITLE
termux-change-rep uses pacman to check mirrors

### ISSUE THREAD

**Issue by Maxython** [termux/termux-tools#11]
This error occurs if the main package manager on the device is `pacman` and `apt` is installed. In the last step of configuring mirrors, it uses the `pkg` command which in turn uses `pacman` due to the `TERMUX_MAIN_PACKAGE_FORMAT` system value.  
```
[*] All mirrors selected
[*] pkg --check-mirror update
:: Synchronizing package databases...
 main is up to date
 x11 is up to date
 root is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by agnostic-apollo** [comment]
If main package manager on device is `pacmac`, then `$TERMUX_APP_PACKAGE_MANAGER` would be `pacman` and `termux-change-repo` will abort before it reaches `pkg` command. How was `termux-tools` installed?

https://github.com/termux/termux-tools/blob/ce464392447f63ba34afe3e288822b6cca7dc238/scripts/termux-change-repo.in#L149-L153

**Comment by Maxython** [comment]
> How was `termux-tools` installed?

Termux-tools was installed from pacman.

**Comment by agnostic-apollo** [comment]
Then why doesn't `termux-change-repo` abort? What's the value of `$TERMUX_APP_PACKAGE_MANAGER` in it?

**Comment by Maxython** [comment]
> Then why doesn't `termux-change-repo` abort? What's the value of `$TERMUX_APP_PACKAGE_MANAGER` in it?

The value of `TERMUX_APP_PACKAGE_MANAGER` is `pacman`, because of this, the `pkg` command uses `pacman`, but need to use `apt` in `termux-change-repo`.

**Comment by agnostic-apollo** [comment]
I was over looking the part that user may optionally not abort. Sorry!

I have merged the pull request. Although, if another package manager is added in distant future, then would need a different solution.

**Comment by agnostic-apollo** [comment]
Apparently, my brain is not working currently, merged without fixing commit message. And any `close` statements must be part of commit message and not just pull request description.
