### ISSUE TITLE
New mirror from Thailand

### ISSUE THREAD

**Issue by kaozaza2** [termux/termux-tools#113]
Hello, I've set up the following mirror for termux-main, termux-x11 and termux-root.

Hostname: [mirrors.omsinchan.ac.th/termux](https://mirrors.omsinchan.ac.th/termux/)
Location: Chonburi, Thailand
Bandwidth: 1 Gbps
Supported protocols: HTTPS
Update frequency: Syncs every days at 01:00

**Comment by 2096779623** [comment]
Please don't enable Cloudflare "Under Attack" mode.

**Comment by kaozaza2** [comment]
> Please don't enable Cloudflare "Under Attack" mode.

Ok, I have updated the WAF Rule.

**Comment by 2096779623** [comment]
Could you please tell us the official English translation of your college, or use your name on the GitHub?

**Comment by kaozaza2** [comment]
Pleade use my Guthub name, not my college name.

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-kao-kittisak) .
