### ISSUE TITLE
i can not update or upgrade or install any packege from the repos

### ISSUE THREAD

**Issue by OmarDLLFile** [termux/termux-tools#116]
hello i have installed termux app on my android phone that running on android 7 operating system my issue is i can not update or upgrade any packege becuse server is down or somthing like that the error messege that acour is like that "**release file for "repor URL" is nor valid yet (invalid for another 6h 39min 17s) updates for this repo will nor be applied**" how i can solve this proplem now with this proplem actually termux is just a apk file i can not do anything on it

**Comment by agnostic-apollo** [comment]
Fix you device time.
