### ISSUE TITLE
New Mirror in India

### ISSUE THREAD

**Issue by niranjan-fartare** [termux/termux-tools#121]
Hello, 

I would like to add a new mirror, https://termux.niranjan.co/ 

Location: Mumbai, India
Speed: 500mbps
Updated every 30 minutes, 

I can increase or decrease the update frequency, how often are the packages updated ??

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-niranjan).
