### ISSUE TITLE
Set up.error

### ISSUE THREAD

**Issue by Powell6221** [termux/termux-tools#133]
Have restart to many time to set up.my account back thus is what it Keep pop error out .

SyntaxError: Non-UTF-8 code starting with '\xa7' in file /storage/emulated/0/ramexfour/ramexfour.py on line 1, but no encoding declared;

![Screenshot_20241007-132429_Termux](https://github.com/user-attachments/assets/709facd3-482d-4538-9182-a2306e43aef3)

**Comment by truboxl** [comment]
That is an error inside the Python script. You need to fix it yourself or ask for help from the original author of the script.
