### ISSUE TITLE
Termux repository problem

### ISSUE THREAD

**Issue by meda767485Adithya** [termux/termux-tools#136]
$ apt update
Get:1 https://hax4us.github.io/TermuxBlack termuxblack InRelease [5692 B]
Hit:2 https://packages.termux.dev/apt/termux-main stable InRelease
Err:1 https://hax4us.github.io/TermuxBlack termuxblack InRelease
  The following signatures were invalid: EXPKEYSIG 4BEE22F9F994D6C4 lokesh pandey <lkpandey950@gmail.com>
Reading package lists... Done
W: https://hax4us.github.io/TermuxBlack/dists/termuxblack/InRelease: Key is stored in legacy trusted.gpg keyring (/data/data/com.termux/files/usr/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://hax4us.github.io/TermuxBlack termuxblack InRelease: The following signatures were invalid: EXPKEYSIG 4BEE22F9F994D6C4 lokesh pandey <lkpandey950@gmail.com>
E: The repository 'https://hax4us.github.io/TermuxBlack termuxblack InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

**Comment by Grimler91** [comment]
Looks like the third party repo hax4us.github.io/TermuxBlack that you have subscribed to is outdated. Report to repository owner, nothing we can do about it

**Comment by meda767485Adithya** [comment]
Ok

**Comment by kkgit2008** [comment]
> that
thanks
