### ISSUE TITLE
New mirror in Jeonnam High School, Gwangju, South Korea

### ISSUE THREAD

**Issue by LeeWonchan4531** [termux/termux-tools#139]
Hello! Jeonnam High School Software Solution Club(Computer Club) in South Korea supports Termux mirroring services!

Hostname: [mirror.jeonnam.school/termux/](https://mirror.jeonnam.school/termux/)
Location: Jeonnam High School, Gwangju, South Korea
Bandwidth: 1 Gbps (Depending on the amount of server connection, the network situation will fluctuate from time to time)
Supported protocols: HTTP, HTTPS
Update period: Syncs every hours
Uptime for the last 1 month: 99.99%

Repository | sources.list entry
-- | --
Main | deb https://mirror.jeonnam.school/termux/termux-main stable main
Root | deb https://mirror.jeonnam.school/termux/termux-root root stable
X11 | deb https://mirror.jeonnam.school/termux/termux-x11 x11 main

**Comment by 2096779623** [comment]
Thanks!
Added to the [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-jeonnam-high-school-software-solution-club)
