### ISSUE TITLE
Notice of Planned Closure of mirrors.qvq.net.cn

### ISSUE THREAD

**Issue by lrinQVQ** [termux/termux-tools#143]
Hey everyone,

Due to increasing concerns regarding regulations and compliance requirements within China,
We have made the difficult decision to shut down the QVQNetwork Open Source Mirrors service.

The service will be officially closed on 1st November, 2024.
After this time, you will no longer be able to access open-source software mirrors through mirrors.qvq.net.cn.

We sincerely apologize for any inconvenience this may cause.
We appreciate your understanding and support.

Sincerely,
QVQNetwork Open Source Mirrors
26th October, 2024

**Comment by agnostic-apollo** [comment]
Is there any specific new regulations or compliance requirements announced by the chinese govt? Any link if yes. Since other chinese mirrors would be affected as well.

**Comment by 2096779623** [comment]
> Are there any specific new regulations or compliance requirements announced by the chinese govt? Any link if yes. Since other chinese mirrors would be affected as well.

This is not an explicit regulation of the Chinese government. They will do it secretly. For example, the official Docker source was banned by GFW a few months ago. Except for some images involving political factors, it is unlikely that our images will be required to be deleted by the Chinese government.

**Comment by agnostic-apollo** [comment]
Right. That sucks (as always). I guess an eye should be kept on this for future.

**Comment by lrinQVQ** [comment]
> 中国政府是否宣布了任何具体的新法规或合规要求？如果有，请提供链接。因为其他中国镜像也会受到影响。

No

It's difficult for us to maintain a good relationship with China. Due to actions like "Operation Card Break(断卡行动)" and "Anti-fraud Centers(反诈中心)" we won't be able to sustain our operations in the future.

*As of now, its still actually available, but it may be shut down at any time.
