### ISSUE TITLE
Termux Issue 

### ISSUE THREAD

**Issue by Sharry7214** [termux/termux-tools#144]
$ apt install jq
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  jq
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 196 kB of archives.
After this operation, 799 kB of additional disk space will be used.
Ign:1 https://md.mirrors.hacktegic.com/termux/termux-main stable/main aarch64 jq aarch64 1.7.1
Ign:1 https://md.mirrors.hacktegic.com/termux/termux-main stable/main aarch64 jq aarch64 1.7.1
Ign:1 https://md.mirrors.hacktegic.com/termux/termux-main stable/main aarch64 jq aarch64 1.7.1
Err:1 https://md.mirrors.hacktegic.com/termux/termux-main stable/main aarch64 jq aarch64 1.7.1
  Could not connect to md.mirrors.hacktegic.com:443 (185.181.228.68), connection timed out
E: Failed to fetch https://md.mirrors.hacktegic.com/termux/termux-main/pool/main/j/jq/jq_1.7.1_aarch64.deb  Could not connect to md.mirrors.hacktegic.com:443 (185.181.228.68), connection timed out
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

How to fix this eror

**Comment by twaik** [comment]
```
termux-change-repo
```

**Comment by Sharry7214** [comment]
Termux apt list start from a,b,c....z but in my termux start from l how to  fix it.
