### ISSUE TITLE
Add a mirror hosted in Japan

### ISSUE THREAD

**Issue by kuroneko6423** [termux/termux-tools#152]
Hello, I have created a new mirror to support the termux package.

Hostname: mirrors.krnk.org/apt/termux/

Location: Tokyo, Japan
Bandwidth: 10Gbps (we use Cloudflare, so we are actually communicating at 100Mbps)
Protocol HTTP, HTTPS (currently IPv4 only)
Synchronization period Every 4 hours (UTC+9)
Provider KuronekoServer (@KuronekoServer https://krnk.org/)

We are considering eliminating Cloudflare and keeping 10Gbps, but only IPv4 will be supported.

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-kuronekoserver).

**Comment by kuroneko6423** [comment]
Thank you very much.
