### ISSUE TITLE
خطای نصب بسته `git`

### ISSUE THREAD

**Issue by Hasibtakar** [termux/termux-tools#156]
### توضیحات
هنگام تلاش برای نصب بسته `git`، با خطای "unable to locate package" مواجه شدم.

### مراحل برای بازتولید مشکل
1. ترمینال Termux را باز کنید.
2. دستور زیر را وارد کنید:

**Comment by Hasibtakar** [comment]
1. ترمینال Termux را باز کنید.
2. دستور زیر را وارد کنید:

**Comment by Hasibtakar** [comment]
### انتظار می‌رود
بسته `git` به‌درستی نصب شود.

### نتیجه واقعی
پیام خطا "unable to locate package git" نمایش داده می‌شود.

**Comment by Hasibtakar** [comment]
### اطلاعات سیستم
- **نسخه Termux**: 0.117
- **سیستم‌عامل**: Android 12
- **معماری**: aarch64

**Comment by twaik** [comment]
Official language of all termux repositories is English. We do not offer support in other languages.
