### ISSUE TITLE
Switching to dynamic motd.sh broken?

### ISSUE THREAD

**Issue by lmservas** [termux/termux-tools#38]
I followed the command given to switch to the dynamic motd.sh

ln -sf $PREFIX/etc/motd.sh ~/.termux/motd.sh

but am still seeing the static motd. Not sure if I missed a step somewhere... I do see the link for motd.sh in $HOME/.termux/

![Screenshot_2023-03-26-07-44-51-95_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/33529347/227783668-97c2ad1b-bd37-4058-aba2-0bc5c3be9c5e.jpg)

**Comment by 2096779623** [comment]
Try `rm $HOME/.hushlogin` .

**Comment by 2096779623** [comment]
![Screenshot_20230326-231640_Pixel](https://user-images.githubusercontent.com/57583560/227785982-25c93116-b146-4b32-aa6f-ec9767ee1e5d.png)

**Comment by lmservas** [comment]
After updating all packages it seems to have switched over to what I thought was the dynamic motd.

![Uploading Screenshot_2023-03-27-17-25-25-97_84d3000e3f4017145260f7618db1d683.jpg…]()
