### ISSUE TITLE
Adding mirror.quantum5.ca to the official mirror list

### ISSUE THREAD

**Issue by quantum5** [termux/termux-tools#42]
Hi! I am running a mirror for termux in Toronto, Ontario, Canada, and I would like it to be added to the [official mirror list](https://github.com/termux/termux-packages/wiki/Mirrors):

#### Mirrors by @quantum5

Hosted in Toronto, Ontario, Canada and updated four times a day.

Repository | sources.list entry
-- | --
Main | `deb http://mirror.quantum5.ca/termux/termux-main stable main`
Root | `deb http://mirror.quantum5.ca/termux/termux-root root stable`
X11 | `deb http://mirror.quantum5.ca/termux/termux-x11 x11 main`

This mirror should be able to handle 1 Gbps. Let me know if there's anything else you need!

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/3d406e9fa14c307d46a1ebc35f03a800de39c8c2) .
