### ISSUE TITLE
[Bug]: `termux-open-url` cannot take spaces

### ISSUE THREAD

**Issue by amaramth** [termux/termux-tools#49]
### Problem description

`termux-open-url 'https://duckduckgo.com/?q=a b'`
says
`Error: Activity not started, unable to resolve Intent`
whereas
`termux-open-url 'https://duckduckgo.com/?q=a%20b'`
works as expected

### System information

* Termux application version: 0.118.0
* Android OS version: 8.0.0
* Device model: F5321

**Comment by agnostic-apollo** [comment]
Should be fixed when `termux-tools` is updated to new version. Termux doesn't parse the uri itself, it is done by android `Uri` class.

https://github.com/termux/TermuxAm/blob/50f9d301811a22fc6a891b975600a21a3d152957/app/src/main/java/com/termux/termuxam/IntentCmd.java#L42

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r49:frameworks/base/core/java/android/net/Uri.java;l=458
