### ISSUE TITLE
Error: commands stopped working with pacman

### ISSUE THREAD

**Issue by Maxython** [termux/termux-tools#5]
I am talking about those commands that were configured with the work of pacman (for example, `pkg` and `termux-info`). This is due to an incorrectly specified value for `TERMUX_MAIN_PACKAGE_FORMAT`, which is listed as debian in the pacman package.

**Comment by Grimler91** [comment]
Should be fixed after exporting TERMUX_PACKAGE_FORMAT and TERMUX_PACKAGE_MANAGER in https://github.com/termux/termux-packages/commit/b044a49d0f70cb3d5d1b13685384888e7d3d9f21, build of termux-tools v1.26.0-1 should work for pacman as well
