### ISSUE TITLE
New mirrors announcement

### ISSUE THREAD

**Issue by zehkaFlokinet** [termux/termux-tools#50]
Hey everybody.
We started mirroring termux on our mirror in romania and will soon add it to mirrors we are currently setting up on different locations across Europe.
Here is the data for the mirror:

```
Hostname: ro.mirror.flokinet.net
Supported protocols: http,https,rsync
Update schedule: *-*-* 00/4:15:00
Connectivity: 1Gbit/s
Provided by: [FlokiNET](https://flokinet.is)
Contact: A well known 3-letter short form of network operation center @ the domain in the "provided by" section
Country: RO
City: Bucharest
Protocols: IPv4 and IPv6
```

If you need any more info we are happy to provide them

**Comment by zehkaFlokinet** [comment]
Hey again,
we deployed another mirror with termux on it, this time in iceland, here is the data:

```
Hostname: is.mirror.flokinet.net
Supported protocols: http,https,rsync
Update schedule: *-*-* 00/4:15:00
Connectivity: 1Gbit/s
Provided by: [FlokiNET](https://flokinet.is)
Contact: A well known 3-letter short form of network operation center @ the domain in the "provided by" section
Country: IS
City: Reykjavík
Protocols: IPv4 and IPv6
```

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/7947d8bf43ac738df858f6dc7ba3939c7fb6d014) .

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/7947d8bf43ac738df858f6dc7ba3939c7fb6d014) .
