### ISSUE TITLE
New mirror mirrors.medzik.dev

### ISSUE THREAD

**Issue by M3DZIK** [termux/termux-tools#52]
Hi, I have made a mirror for termux in Germany, Frankfurt and would like it to be added to the official mirror list.

**Mirror by: @M3DZIK**

Repository | sources.list entry
-- | --
Main | deb https://mirrors.medzik.dev/termux/termux-main stable main
Root | deb https://mirrors.medzik.dev/termux/termux-root root stable
X11 | deb https://mirrors.medzik.dev/termux/termux-x11 x11 main

The server has a bandwidth of 4Gbps. It is updated every ~15 minutes.

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-m3dzik) .
