### ISSUE TITLE
New mirror announcement (yet again)

### ISSUE THREAD

**Issue by zehkaFlokinet** [termux/termux-tools#54]
Hey everybody.
After setting up mirrors in Romania and Iceland in #50 we now also have a mirror in the Netherlands available

Hostname: nl.mirror.flokinet.net
Supported protocols: http,https,rsync
Update schedule: *-*-* 00/4:36:00
Connectivity: 1Gbit/s
Provided by: [FlokiNET](https://flokinet.is)
Contact: A well known 3-letter short form of network operation center @ the domain in the "provided by" section
Country: RO
City: Bucharest
Protocols: IPv4 and IPv6

If you need any more info we are happy to provide them

**Comment by Grimler91** [comment]
Added in https://github.com/termux/termux-tools/pull/94, will be part of next termux-tools update, thanks!
