### ISSUE TITLE
New mirror mirrors.cfe.re

### ISSUE THREAD

**Issue by cfxproxy** [termux/termux-tools#56]
Hi, I have made a mirror for termux in Poland, Kalisz and would like it to be added to the official mirror list. 
Mirror by: [@cfxproxy](https://github.com/cfxproxy)

Repository | sources.list entry
-- | --
Main | deb https://mirrors.cfe.re/termux/termux-main stable main
Root | deb https://mirrors.cfe.re/termux/termux-root root stable
X11 | deb https://mirrors.cfe.re/termux/termux-x11 x11 main

<p dir="auto">The server has a bandwidth of 1Gbps. It is updated every day</p>

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-cfxproxy) .
