### ISSUE TITLE
New mirror: mirrors.rda.run

### ISSUE THREAD

**Issue by rdeavila** [termux/termux-tools#59]
Hello,

I've created a new Termux mirror on my home lab (next to my AlmaLinux mirror), and I want to share it publicly.

* Hostname: `mirrors.rda.run`
* Supported protocols: `https`
* Update schedule: `0 * * * *`
* Connectivity: `500Mbit/s`
* Provided by: [Rodrigo de Avila](https://rda.run)
* Contact: `mirrors@rda.run`
* Country: `BR`
* City: `Brochier`
* Protocols: `IPv4 and IPv6` (Behind Cloudflare)

Please let me know if you have any questions. Thanks!

**Comment by 2096779623** [comment]
Thanks!

> Would it be possible to enable rsync on the mirror (it can be password protected/private if you prefer)? 
That would enable us to track the mirror status with tools like [mirrorbits](https://github.com/etix/mirrorbits/): https://mirror.termux.dev/?mirrorstats, and redirect users to it based on geo-location.

Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-rodrigo-de-avila).
https://github.com/termux/termux-tools/commit/945272b2504e8f05ef7f67028c4086a3cb2704c5

**Comment by rdeavila** [comment]
> Would it be possible to enable rsync on the mirror (it can be password protected/private if you prefer)?

Sure! The server is connected to Cloudflare via Cloudflare Tunnel, but I'll try to share via rsync too.

**Comment by rdeavila** [comment]
Hi @2096779623

Can you please try `rsync://rsync.mirrors.rda.run/termux`?

```
[rdeavila@zenvia-1M4CM63:~]$ rsync --list-only rsync://rsync.mirrors.rda.run/termux
drwxr-xr-x             92 2022/12/08 16:36:08 .
drwxr-xr-x             18 2022/12/08 16:35:58 termux-main-21
drwxr-xr-x             34 2022/12/26 06:28:47 termux-main
drwxr-xr-x             18 2022/12/10 07:53:27 termux-root
drwxr-xr-x             18 2022/12/08 16:35:44 termux-x11
```

**Comment by 2096779623** [comment]
Work fine,thanks!

CC: @Grimler91
