### ISSUE TITLE
New mirror: mirrors.qvq.net.cn

### ISSUE THREAD

**Issue by lrinQVQ** [termux/termux-tools#63]
Hey,I setup a mirror for termux in Chongqing, China and would like added to the official mirror list.
Mirror by: @lrinQVQ

| Repository                                             | sources.list entry                                                    |
|:-------------------------------------------------------|:----------------------------------------------------------------------|
| [Main](https://github.com/termux/termux-packages)      | `deb https://mirrors.qvq.net.cn/termux/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages) | `deb https://mirrors.qvq.net.cn/termux/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)          | `deb https://mirrors.qvq.net.cn/termux/termux-x11 x11 main`     |

The server has 1Gbps bandwidth, It is updated every 1.5-2.5h(Randomized Delay)

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-lrinqvq) .

**Comment by lrinQVQ** [comment]
Update: IPv6 support added

**Comment by 2096779623** [comment]
> Update: IPv6 support added

Updated.
https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-lrinqvq

**Comment by lrinQVQ** [comment]
Notice of Planned Closure of mirrors.qvq.net.cn

Hey everyone,

Due to increasing concerns regarding regulations and compliance requirements within China,
We have made the difficult decision to shut down the QVQNetwork Open Source Mirrors service.

The service will be officially closed on 1st November, 2024.
After this time, you will no longer be able to access open-source software mirrors through mirrors.qvq.net.cn.

We sincerely apologize for any inconvenience this may cause.
We appreciate your understanding and support.

Sincerely,
QVQNetwork Open Source Mirrors
26th October, 2024
