### ISSUE TITLE
New mirror in Amsterdam, NL

### ISSUE THREAD

**Issue by NickBouwhuis** [termux/termux-tools#69]
Hostname: mirror.bouwhuis.network
Supported protocols: http,https,rsync
Update schedule: `15 */6 * * *`
Connectivity: 10Gbit/s
Provided by: [bouwhuis.network](https://bouwhuis.network/)
Contact: A well known 3-letter short form of network operation center @ the domain in the "provided by" section
Country: NL
City: Amsterdam
Protocols: IPv4 and IPv6

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-bouwhuisnetwork) .

**Comment by NickBouwhuis** [comment]
Cool! Just wanted to add that `15 */6 * * *` means the mirror is updated at minute 15 past every 6th hour.. 

So updates are fetched every 6 hours.

I can increase the frequency if desired.

**Comment by 2096779623** [comment]
> Cool! Just wanted to add that `15 */6 * * *` means the mirror is updated at minute 15 past every 6th hour..
> 
> So updates are fetched every 6 hours.
> 
> I can increase the frequency if desired.

It has been modified to the correct synchronization time, but [crontab.guru](https://crontab.guru/#15_*/6_*_*_*) told me that it is "At minute 15 past every 6th hour." at first.

Most mirrors are updated once a day.
