### ISSUE TITLE
New mirror repo

### ISSUE THREAD

**Issue by MyDapitt** [termux/termux-tools#71]
### Why is it worth to add this package?

Hi, I just created a termux repository mirror. Can you help me add it to the termux-tools package?

Mirror link:
[termux-main](https://tmx.xvx.my.id/apt/termux-main/)
[termux-root](https://tmx.xvx.my.id/apt/termux-root/)
[x11](https://tmx.xvx.my.id/apt/termux-x11/)

Information:
The mirror comes from Jakarta, Indonesia. It is hosted by Linode.
Thanks for your help ~

### Source code URL

https://tmx.xvx.my.id

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by Grimler91** [comment]
Hi, thanks! 

Is it possible to enable rsync on the repo? 
With rsync we can keep track of the mirror status (like when it was updated last time, if it is accessible)

**Comment by 2096779623** [comment]
> Is it possible to enable rsync on the repo? With rsync we can keep track of the mirror status (like when it was updated last time, if it is accessible)

Btw, Has mirror.termux.dev been fixed now?

**Comment by Grimler91** [comment]
> > Is it possible to enable rsync on the repo? With rsync we can keep track of the mirror status (like when it was updated last time, if it is accessible)
> 
> Btw, Has mirror.termux.dev been fixed now?

No, not yet, will try to look at it this week

**Comment by Grimler91** [comment]
> Can you give me the command? I will do it.

If rsync is installed you can create a rsyncd config looking something like:

```
$ cat /etc/rsyncd.conf
[termux]
  path =  /srv/termux/aptly/public/
  read only = yes
  uid = 7205
  gid = 7205
```

where 7205 is the user and group id of a dedicated `rsync` user.

You could also password protect it by adding something like

```
auth users = username
secrets file = /var/rsyncd.secrets
```

where `/var/rsyncd.secrets` contains plaintext `username:password` (if you set up a username and password then please share it with me in private so that I can add it to our mirror checker config). 

You then enable the rsync.service and we should be able to run (something like) `rsync -r -L rsync://tmx.xvx.my.id/apt` to check status of your mirror

**Comment by 2096779623** [comment]
> I'm not familiar with rsync, can you install it? I will give you the VPS information, where can I contact you personally?

If u are using debian/ubuntu,use the following command to install it:
```bash
apt install rsync
```

**Comment by 2096779623** [comment]
> And then?

Follow the steps to config rsync.
https://github.com/termux/termux-tools/issues/71#issuecomment-1929143721

**Comment by 2096779623** [comment]
What is its bandwidth?

**Comment by 2096779623** [comment]
> The mirror comes from Jakarta, Indonesia. It is hosted by Linode.

Now its IP location is Singapore.

**Comment by 2096779623** [comment]
> 10 gbps

The ASN of this IP belongs to Akamai Connected Cloud, so the large bandwidth becomes normal :) .

**Comment by Grimler91** [comment]
Added the mirror to the repo in https://github.com/termux/termux-tools/commit/682d09fcb115698f35af2791c5271a95288863fc, thanks!
