### ISSUE TITLE
[Bug]: New Mirror in Lisbon, Portugal

### ISSUE THREAD

**Issue by tomas347** [termux/termux-tools#75]
### Problem description

Hi,

I'm creating this issue to donate a new mirror in Lisbon Portugal.
The mirror is available via RSYNC, HTTP and HTTPS @ mirror.leitecastro.com/termux.
The node is connected at 20Gbps and is IPv4 and IPv6 enabled.
It is currently syncing hourly from rsync://packages.termux.dev/termux
Let me know if you want to reduce the frequency of the sync.

Regards,

Tomás

### What steps will reproduce the bug?

N/A

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
Thanks, how often does it sync?

**Comment by tomas347** [comment]
Currently syncing hourly. I can change the sync frequency if needed
