### ISSUE TITLE
New Mirror in Vietnam

### ISSUE THREAD

**Issue by HoangTheBoss** [termux/termux-tools#77]
I'm setting up and syncing a new mirror, details are as follows:

Hostname: mirrors.nguyenhoang.cloud
Supported protocols: https only (for now, I'm working on providing rsync)
Update schedule: Twice a day (53 */12 * * * GMT+7)
Connectivity: 1Gbit/s
Provided by: [Nguyen Hoang](https://github.com/HoangTheBoss)
Contact: me@nguyenhoang.cloud
Country: VN
City: Hanoi
Protocols: IPv4 Only

Please check and implement. Thank you.

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-nguyen-hoang).

**Comment by huupoke12** [comment]
@HoangTheBoss Could you check the mirror for issues? It hasn't been updated since April 8 (`lastsync` is `1712555401`).

**Comment by huupoke12** [comment]
@HoangTheBoss Could you check the mirror for issues, it has been more than two months since the last sync.

**Comment by HoangTheBoss** [comment]
> @HoangTheBoss Could you check the mirror for issues, it has been more than two months since the last sync.

Sorry for the inconvenience and delay, I missed both the GitHub notification and sync alerts.
The site `mirror.termux.dev` is not reachable for me, which is crucial for syncing, and I'll try to resolve this in the next week.

**Comment by HoangTheBoss** [comment]
> @HoangTheBoss Could you check the mirror for issues, it has been more than two months since the last sync.

The mirror is now syncing from `grimler.se`, it should be up-to-date in about an hour from this message.

**Comment by huupoke12** [comment]
@HoangTheBoss Can you check the mirror again? It seems to be down for a week.
