### ISSUE TITLE
New Mirror in Singapore

### ISSUE THREAD

**Issue by karibuTW** [termux/termux-tools#79]
Hello
I am the mirror admin of mirror.freedif.org.
We have recently upgraded our bandwidth and hardware and are able to support new projects. 
I would be glad to support Termux with a new mirror in Singapore

http://mirror.freedif.org/termux/
https://mirror.freedif.org/termux/
rsync://mirror.freedif.org/termux/

Location: Singapore (SG)
Bandwidth: 10 GBPS
Hourly refresh - Full Rsync
Contact: karibu at freedif (dot) com

Let me know if you need any other information

Thank you

**Comment by 2096779623** [comment]
Thanks, added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-karibu).
