### ISSUE TITLE
Add mirror.accum.se mirror

### ISSUE THREAD

**Issue by ZNikke** [termux/termux-tools#89]
Hi!

Our mirror was previously registered as ftp.acc.umu.se, but while the 
old host name still works it looks like it's been removed from your 
list of mirrors (which is interesting, since our mirror was one of the first IIRC).

Anyhow, I've updated our setup to mirror from packages.termux.dev instead of grimler.se according to the instructions on https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories

Mirror hosted by:

[Academic Computer Club in Umeå, Sweden](https://www.accum.se/)

Contact email:

ftp-adm@accum.se

Access URLs:

http://mirror.accum.se/mirror/termux.dev/
https://mirror.accum.se/mirror/termux.dev/
rsync://mirror.accum.se/mirror/termux.dev/

Bandwidth:

200 Gbps (yes Gbps)

Sync frequency:

Every 4th hour

Mirror status URL:

https://mirror.accum.se/mirror/

**Comment by agnostic-apollo** [comment]
Already exists.

https://github.com/termux/termux-tools/commit/90cf0f20ab0219f4c49e52a98fe8e9e879734ef9

**Comment by ZNikke** [comment]
Ah, OK. It's not listed on https://github.com/termux/termux-packages/wiki/Mirrors and https://mirror.termux.dev/?mirrorstats was unresponsive so I assumed that the list in the wiki was the correct one...

Sorry for the noise.

**Comment by agnostic-apollo** [comment]
mirrorstats got broken a while back if I remember correctly.

Your mirror should be added to the wiki though, someone else should be able to do that.

**Comment by Grimler91** [comment]
Added to the wiki page now as well (seems I forgot that before), thanks!
