### ISSUE TITLE
Repository Mirror

### ISSUE THREAD

**Issue by danyael031** [termux/termux-tools#90]
I have created a mirror of the termux repository:

https://termux.danyael.xyz/termux

It is syncing each 6 hours from the main repository packages.termux.dev based on the instructions from 
https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories#mirroring-with-rsync

Please consider add it to the mirror list.

**Comment by 2096779623** [comment]
Please tell us the bandwidth.
