### ISSUE TITLE
New Mirror in Porto, Portugal

### ISSUE THREAD

**Issue by 7zx** [termux/termux-tools#92]
As the administrator of this mirror, I guarantee continuous uptime and plenty of bandwidth. I'm fully committed to supporting the Termux community's needs effectively.

- **Hostname:** [mirror.polido.pt/termux](https://mirror.polido.pt/termux/)
- **Location:** Porto, Portugal
- **Connectivity:** 1 Gbps
- **Supported protocols:** HTTP, HTTPS, rsync
- **Update period:** Syncs occur nightly according to the Europe/Lisbon timezone. (This schedule can be adjusted upon request.)
- **IP version:** IPv4 only, for now.

**Comment by Grimler91** [comment]
Added in https://github.com/termux/termux-tools/pull/94, will be part of next termux-tools update, thanks!
